# Generated by Django 4.0.2 on 2022-03-08 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_address_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='middle_name',
        ),
    ]
