# Generated by Django 4.0.2 on 2022-03-11 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_address_middle_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='address_1',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='address',
            name='address_2',
        ),
    ]
