# Generated by Django 4.0.2 on 2022-03-13 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_address_1_address_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('stripe_payment_intent', models.CharField(max_length=2000)),
                ('has_paid', models.BooleanField(default=False)),
                ('status', models.CharField(max_length=10)),
                ('address', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.address')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
            ],
        ),
    ]
